services:
  - type: web
    name: tabeeb-backend
    env: node
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OCR_SERVICE_URL
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: CORS_ORIGIN
        sync: false
